create database PAPELARIA;
use PAPELARIA;



-- Criação da tabela 'produtos'
CREATE TABLE tbProduto (
    PRO_CODIGO INT AUTO_INCREMENT PRIMARY KEY,
    PRO_NOME VARCHAR(255) NOT NULL,
    PRO_DESCRICAO VARCHAR(255),
    PRO_PRECO DECIMAL(10, 2) NOT NULL,
    PRO_QUANTIDADE_ESTOQUE INT NOT NULL
);

-- Criação da tabela 'pedidos'
CREATE TABLE tbPedido (
    PED_CODIGO INT AUTO_INCREMENT PRIMARY KEY,
    PED_NOME_CLIENTE VARCHAR(255) NOT NULL,
    PED_DATA_PEDIDO DATE NOT NULL
);

-- Criação da tabela 'itens_pedido' para representar os produtos em um pedido
CREATE TABLE tbItemPedido(
    IPE_CODIGO INT AUTO_INCREMENT PRIMARY KEY,
    PED_CODIGO INT,
    PRO_CODIGO INT,
    IPE_QUANTIDADE INT NOT NULL,
    IPE_PRECO_UNITARIO DECIMAL(10, 2) NOT NULL,
    FOREIGN KEY (PED_CODIGO) REFERENCES tbPedido(PED_CODIGO) ON DELETE CASCADE,
    FOREIGN KEY (PRO_CODIGO) REFERENCES tbProduto(PRO_CODIGO) ON DELETE SET NULL
);
