create database PAPELARIA;

use PAPELARIA;

CREATE TABLE IF NOT EXISTS `PAPELARIA`.`tbProduto` (
  `PRO_CODIGO` INT NOT NULL AUTO_INCREMENT,
  `PRO_NOME` VARCHAR(30) NOT NULL,
  `PRO_PRECO` DECIMAL(6,2) UNSIGNED NOT NULL,
  `PRO_QUANTIDADE_ESTOQUE` INT UNSIGNED NOT NULL,
  `PRO_CATEGORIA` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`PRO_CODIGO`))
;

CREATE TABLE IF NOT EXISTS `PAPELARIA`.`tbVenda` (
  `VEN_CODIGO` INT NOT NULL AUTO_INCREMENT,
  `VEN_DATA_VENDA` DATE NOT NULL,
  `VEN_QUANTIDADE_PRODUTOS` INT UNSIGNED NOT NULL,
  `VEN_NOME_CLIENTE` VARCHAR(60) NOT NULL,
  `PRO_CODIGO` INT NOT NULL,
  PRIMARY KEY (`VEN_CODIGO`),
  INDEX `fk_tbVenda_1_idx` (`PRO_CODIGO` ASC) VISIBLE,
  CONSTRAINT `fk_tbVenda_1`
    FOREIGN KEY (`PRO_CODIGO`)
    REFERENCES `PAPELARIA`.`tbProduto` (`PRO_CODIGO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
;